apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank
  labels:
    app: bank
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
      containers:
      - name: bank
        image: glarimy/bank
        ports:
        - containerPort: 8080