---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: 5985
  username: <%= ENV["machine_user"] %>
  password: <%= ENV["machine_pass"] %>
  elevated: false
  elevated_username: <%= ENV["machine_user"] %>
  elevated_password: <%= ENV["machine_pass"] %>
  require_chef_omnibus: 13.8.5

provisioner:
  name: chef_zero

platforms:
  - name: windows-2012R2
    driver:
      box: mwrock/Windows2012R2

suites:
  - name: default
    run_list:
      - recipe[test_archive]
